### ISSUE TITLE
Discussion: Increase Backup Witness Pay To Be 5x T20 rate

### ISSUE THREAD

**Issue by Rishi556** [hive-engine/hivesmartcontracts#35]
Backup witnesses get selected less often than regular witnesses, and to compensate them for that, Hive pays them at an increased rate of 5x of T20. Engine should consider doing the same as backups earn a lot less than T20 as of now.

**Comment by Rishi556** [comment]
For this, the biggest question is where should the extra come from? Personally I'm in favor of reducing T20 pay per block in order to reach this to not increase inflation.

**Comment by ervin-lemark** [comment]
basic reward, sort of. I like it. the potential amount can be calculated ...

**Comment by forkyishere** [comment]
Does not hurt much to try and see the consequences. I would not bother at least... to see if that actually brings more interest from new witnesses or if current backup ones will become more resilient during bad times... which is where I see most of the value.

**Comment by bt-cryptomancer** [comment]
I'm rather neutral on this, don't have strong feelings either way.  I'd be fine with it if you guys are in agreement.
